### ISSUE TITLE
type mapping auf heinzel standart

### ISSUE THREAD

**Issue by sprengr** [heinzelmannchen/BA#18]

**Comment by sprengr** [comment]
ha ma chli zämetreit:
https://github.com/heinzelmannchen/BA-Stuff/wiki/Daten---Typen

ich wür diä gliiche type wiä knex bereits verwändet näh.
vorteil: scho umgsetzt (müsst mä halt na teste), funktioniert für diä dbs wo mier bruuched
nachteil: me abhängigkeit vo knex, mär "beschränket" ois uf folgendi datetype: Integer, TinyInteger, Float, Decimal, Boolean, Enum, DateTime, Timestamp, Bit, Binary, Uuid, Json

**Comment by stoeffel** [comment]
schöne aufstellung.
ich werd mir das bis am montag bez. morgen abend auch nochmals einwenig zu gemüte führen.
