### ISSUE TITLE
Konfiguration aufsetzen

### ISSUE THREAD

**Issue by sprengr** [heinzelmannchen/BA#47]
- Konfigmodule einbauen
- Beschreiben wie Config aufgebaut ist

**Comment by stoeffel** [comment]
# Konfiguration

Die Config ist als JSON in drei Abschnitte unterteilt Domains, Templates, und Generators.
Grundsätzlich soll die Struktur einer Config für ein Projekt sich nicht von der Globalen Config unterscheiden. Es soll dem User einfach möglich sein die Config nach seinen Wünschen anzupassen.

## Templates

Im Abschnitt `Templates` werden die Repositories der Templates welche in den Domains verwendet werden
angegeben. Es kann festgelegt werden, welche Version eines Templates verwendet werden soll, 
indem man die Version mit einem `#` an die Url anhängt.

``` JSON
{
    "templates": {
        "formView": "http://yourrepo.com/formView.git#1.0.1",
        "listView": "http://yourrepo.com/listView.git#2.0.1"
    }
}
```

## Generators

Im Abschnitt `Generators` werden die Repositories der Generatoren angegeben.
Falls ein Generator weitere Konfigurationen benötigt, kann dies hier angegeben werden.

``` JSON
{
    "generators": {
        "pg": {
            "npm": "heinzelmannchen-gen-pg",
            "config": {
                "charset": "utf8",
                "database": "heinzel",
                "host": "127.0.0.1",
                "user": "user",
                "password": "password"
            }
        },
        "json": "http://yourrepo.com/json.git#1.0.1"
    }
}
```

## Domains

In diesem Abschnitt werden die Generatoren mit den Templates verlinkt.
Die Domain hat einen Namen (im Beispiel `extViews` darin gibt man zu den benötigten Templates den Outputpfad an und einen Generator. Es kann auch ein globaler Generator für alle Templates in einer Domain angegeben werden.

``` JSON
{
    "domains": {
        "extViews": {
            "formView": {
                output: "app/{{ tablename }}/form.js",
                generator: "pg"
            },
            "listView": {
                output: "app/{{ tablename }}/form.js"
            },
            "generator": "inline"
        }
    }
}
```
