### ISSUE TITLE
PM - Werkzeuge aufsetzen

### ISSUE THREAD

**Issue by stoeffel** [heinzelmannchen/BA#5]
SP: 3
- github issues
- burndownchart erstellen
-

**Comment by sprengr** [comment]
http://burndown.io/#heinzelmannchen/BA-Stuff/1

**Comment by stoeffel** [comment]
https://chrome.google.com/webstore/detail/github-points-story-point/honbjgnddmnmakomlgibfljnhjnhoahj?hl=en
