### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by sprengr** [heinzelmannchen/BA#53]
- Erstellt Config File im aktuellem Ordner
- Benötigte Informationen werden übergeben
- nimmt objekt mit Arrays entegegen templates/generators/domains)
  - templates/generators werden automatisch installiert und im config eingetragen
  - domains wird die namen-verschachtelung erstellt ("ext.views.list" -> { ext: { views: { list: ... } } }

**Comment by stoeffel** [comment]
heinzel.init({
    gens: ['asd', a'asd'],
    templ: [],
    domains: [{
        name: 'ext.form'
        template: 'asd'
        gen : 'asd'
        output: 'asdasd'
    }]

heinzel.addDomain = function (name, config)

> heinzel init
> 
> heinzel add domain --name=foo --template=bla --generator=blub --output=foobar.md

**Comment by stoeffel** [comment]
WIP
