### ISSUE TITLE
npm Funktionalität auslagern

### ISSUE THREAD

**Issue by sprengr** [heinzelmannchen/BA#54]
- aus Generator Repo ausbauen
- tests anpassen
- neues Repo aufsetzen

**Comment by sprengr** [comment]
heinzelmannchen-npm

**Comment by stoeffel** [comment]
![screen shot 2014-04-14 at 16 04 14](https://cloud.githubusercontent.com/assets/1217681/2696015/be9f0ebc-c3dd-11e3-82f4-75597d1d0054.png)

**Comment by sprengr** [comment]
neu mit npmjs
